In [1]:

# A Python library is a collection of
# functions and methods that allows you 
# to perform many actions without writing your own code. 
# We use Python libraries to save time and effort by reusing 
# code that others have already written, making it easier to perform 
# complex tasks such as data analysis, web development, andmachine learning.

In [5]:
import numpy as np
arr=np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

In [8]:
arr.ndim

2

In [9]:
arr.shape

(3, 4)

In [10]:
arr.size

12

In [11]:
arr1=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

In [15]:
arr1[0]

array([1, 2, 3, 4])

In [13]:
arr2=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

In [18]:
arr2[2,3]

12

In [20]:
arr2[:, 1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [38]:
import random
arr4=np.random.rand(3,3)

In [39]:
arr4

array([[0.49516402, 0.74599953, 0.46968886],
       [0.11089936, 0.99654179, 0.22798546],
       [0.90996681, 0.33558245, 0.41387787]])

In [43]:
np.random.rand(3, 2)

array([[0.35988385, 0.72467239],
       [0.8105647 , 0.00917655],
       [0.38363404, 0.66306426]])

In [41]:
np.random.randn(3, 2)

array([[-0.85170008,  0.79177349],
       [-0.52900854,  2.12338691],
       [ 0.08113584,  1.19644292]])

In [44]:
#  the main difference is in the distribution of the generated numbers: np.random.rand generates numbers from a uniform distribution, while np.random.randn generates numbers from a standard normal distribution.






In [47]:
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [48]:
arr2.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [55]:
matrixA=arr1

In [56]:
matrixB=arr2

In [58]:
matrixA*matrixB

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [60]:
matrixA+matrixB

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [61]:
matrixB-matrixA

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [62]:
matrixB/matrixA

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
matrixA@matrixB #matrix multiplication would not be possible 

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [64]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [68]:
arr1.reshape(2,6) #reshape function change the row and column or shape of the array.

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [69]:
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

arr1.expand_dims()

In [71]:
arr3=np.expand_dims(arr1,axis=0)

In [72]:
arr3

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [73]:
# Broadcasting in NumPy is a 
# mechanism that allows 
# arrays of different shapes to be combined in arithmetic operations. It helps to perform operations on arrays that would otherwise be incompatible in terms of shape, by implicitly expanding the smaller arrays 
# to match the shape of the larger arrays.

In [74]:
#The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix.

In [76]:
arr5=[[1,2],[3,4]]
arr6=np.linalg.inv(arr5)

In [77]:
arr6

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [ ]:
#We can use the np.ndarray.byteswap method 
# in NumPy to swap the byte order of an array. 
# This method swaps the byte order of the array elements in place.